packages:
  - packages/*
  - apps/*
  - pocs/*
  - pocs/ledger-button-webcomponent-poc/examples/*

catalog:
  "@ledgerhq/coin-framework": ^5.0.0
  bignumber.js: ^9.1.2
  "@angular/animations": ^17.0.0
  "@angular/common": ^17.0.0
  "@angular/compiler": ^17.0.0
  "@angular/compiler-cli": ^17.0.0
  "@angular/core": ^17.0.0
  "@angular/platform-browser": ^17.0.0
  "@angular/platform-browser-dynamic": ^17.0.0
  "@babel/core": ^7.14.5
  "@babel/preset-react": ^7.14.5
  "@eslint/compat": ^1.1.1
  "@eslint/eslintrc": ^2.1.1
  "@eslint/js": ^9.8.0
  "@headlessui/react": ^2.2.7
  "@ledgerhq/context-module": 1.14.1
  "@ledgerhq/device-management-kit": 1.1.0
  "@ledgerhq/device-signer-kit-ethereum": 1.11.1
  "@ledgerhq/device-transport-kit-web-ble": 1.3.2
  "@ledgerhq/device-transport-kit-web-hid": 1.2.3
  "@ledgerhq/device-trusted-app-kit-ledger-keyring-protocol": 0.4.1
  "@ledgerhq/lumen-design-core": ^0.0.55
  "@lit/context": 1.1.6
  "@next/eslint-plugin-next": ^15.2.4
  "@nx/devkit": 22.0.1
  "@nx/eslint": 22.0.1
  "@nx/eslint-plugin": 22.0.1
  "@nx/jest": 22.0.1
  "@nx/js": 22.0.1
  "@nx/next": 22.0.1
  "@nx/playwright": 22.0.1
  "@nx/react": 22.0.1
  "@nx/storybook": 22.0.1
  "@nx/vite": 22.0.1
  "@nx/web": 22.0.1
  "@open-wc/testing": ^4.0.0
  "@playwright/test": ^1.36.0
  "@storybook/addon-coverage": ^2.0.0
  "@storybook/addon-docs": 9.0.17
  "@storybook/react-vite": 9.0.17
  "@storybook/test-runner": ^0.23.0
  "@storybook/web-components": ^9.0.17
  "@storybook/web-components-vite": 9.0.17
  "@swc-node/register": ~1.9.1
  "@swc/cli": ~0.6.0
  "@swc/core": ~1.5.7
  "@swc/helpers": ~0.5.11
  "@testing-library/dom": 10.4.0
  "@testing-library/react": 16.1.0
  "@types/jsonwebtoken": ^9.0.9
  "@types/node": 22.10.1
  "@types/pako": ^2.0.4
  "@types/react-dom": 19.0.0
  "@vitejs/plugin-react": ^4.2.0
  "@vitest/coverage-v8": ^3.0.5
  "@vitest/ui": ^3.0.0
  autoprefixer: 10.4.17
  bignumber.js: ^9.1.2
  chalk: ^5.4.1
  class-variance-authority: ^0.7.1
  concurrently: ^9.1.2
  danger: ^13.0.4
  esbuild: ^0.20.0
  esbuild-node-externals: ^1.9.0
  eslint: ^9.8.0
  eslint-config-next: ^15.2.4
  eslint-config-prettier: ^10.0.0
  eslint-plugin-import: 2.31.0
  eslint-plugin-jsx-a11y: 6.10.1
  eslint-plugin-playwright: ^1.6.2
  eslint-plugin-react: 7.35.0
  eslint-plugin-react-hooks: 5.0.0
  eslint-plugin-simple-import-sort: ^12.1.1
  eslint-plugin-storybook: 9.0.17
  ethers: ^6.15.0
  fake-indexeddb: ^6.0.1
  gitmoji-cli: ^9.7.0
  globals: 16.0.0
  happy-dom: ^20.0.0
  http-server: ^14.1.1
  inversify: ^7.5.1
  jiti: 2.4.2
  jsonc-eslint-parser: ^2.1.0
  lit: 3.3.1
  lottie-web: ^5.12.2
  motion: ^12.23.6
  next: 15.5.8
  nextra: ^3.0.13
  nextra-theme-docs: ^3.0.15
  nx: 22.0.1
  pako: ^2.0.4
  postcss: 8.4.38
  prettier: ^3.6.1
  prettier-plugin-tailwindcss: ^0.6.13
  purify-ts: 2.1.0
  react-medium-image-zoom: 5.1.8
  reflect-metadata: ^0.2.2
  rxjs: 7.8.2
  semver: ^7.6.0
  shadow-dom-testing-library: ^1.12.0
  storybook: 9.0.17
  swc-loader: 0.1.15
  "@tailwindcss/cli": ^4.1.17
  "@tailwindcss/postcss": ^4.1.17
  "@tailwindcss/vite": ^4.1.17
  tailwindcss: ^4.1.17
  tailwind-merge: ^1.14.0
  tailwindcss: 3.4.16
  ts-jest: ^29.1.0
  ts-node: 10.9.1
  tsc-alias: ^1.8.10
  tslib: ^2.3.0
  typescript: 5.9.3
  typescript-eslint: 8.46.2
  uuid: ^11.1.0
  verdaccio: ^6.0.5
  vite: 7.1.9
  vite-plugin-dts: ~4.5.0
  vite-plugin-elm: ^3.0.1
  vitest: ^3.0.0
  wait-on: ^8.0.3
  zod: ^4.1.5
  zone.js: ~0.14.0
  zx: ^8.1.7

catalogMode: prefer

catalogs:
  react18:
    '@types/react': 18.3.12
    react: 18.3.1
    react-dom: 18.3.1
  react19:
    '@types/react': 19.0.0
    react: 19.0.0
    react-dom: 19.0.0

cleanupUnusedCatalogs: true

overrides:
  purify-ts: 2.1.0
