import "./global.css";

export const metadata = {
  title: "Welcome to test-dapp",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="wrapper">
          <div className="toolbar">
            <p>Ledger Test Dapp for Ledger Button (EIP-1193/EIP-6963)</p>
          </div>
          <main className="content">{children}</main>
        </div>
      </body>
    </html>
  );
}
