import "./global.css";
import "@ledgerhq/ledger-button/styles.css";

export const metadata = {
  title: "Welcome to test-dapp",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="wrapper">
          <div className="toolbar">
            <p>Logo</p>
            <p>Menu</p>
          </div>
          <main className="content">
            {children}
          </main>
        </div>
        <footer className="footer">
          <p id="love">
            Carefully crafted with
            <svg
              fill="currentColor"
              stroke="none"
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"
              />
            </svg>
          </p>
        </footer>
      </body>
    </html>
  );
}
