import "./global.css";
import "@ledgerhq/ledger-button/styles.css";

export const metadata = {
  title: "Welcome to test-dapp",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
