name: "[CI] Scan Sonar - Called"

on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
      should_download_coverage:
        required: false
        default: false
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  scan-sonar:
    name: "SonarCloud Analysis"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref || github.sha }}
          fetch-depth: 0

      - name: Download unit test coverage
        if: ${{ inputs.should_download_coverage }}
        uses: actions/download-artifact@v7
        with:
          name: coverage
          path: packages

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
